site_name: Ch-aOS Documentation
site_url: https://Ch-aOS-Ch.github.io/Ch-aOS/
repo_url: https://github.com/Ch-aOS-Ch/Ch-aOS
repo_name: Ch-aOS-Ch/Ch-aOS

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

  features:
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.top

plugins:
  - search
  - mkdocstrings:
      handlers:
         python:
           paths: ['cli/src']

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 'Introduction': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'Core Concepts': 'core-concepts.md'
  - 'The Chopping Board': 'chopping-board.md'
  - 'Glossary': 'glossary.md'
  - 'Commands':
    - 'Apply': 'Commands/apply.md'
    - 'Management': 'Commands/management.md'
    - 'Styx': 'Commands/styx.md'
    - 'Explain': 'Commands/explain.md'
    - 'Team': 'Commands/team.md'
    - 'Secrets': 'Commands/secrets.md'
    - 'Ramble': 'Commands/ramble.md'
  - 'Advanced':
    - 'Fleet Management': 'Advanced/fleet.md'
    - 'Boats for your Fleet': 'Advanced/boats.md'
    - 'Pyinfra Connectors': 'Advanced/connectors.md'
    - 'Secret Providers': 'Advanced/providers.md'
    - 'Logbook': 'Advanced/logbook.md'
    - 'Composability': 'Advanced/composability.md'
    - 'SDK':
      - 'Overview': 'Advanced/SDK/overview.md'
      - 'Orchestration': 'Advanced/SDK/orchestration.md'
      - 'Fleet Management': 'Advanced/SDK/fleet.md'
      - 'Interfaces and Flags': 'Advanced/SDK/interfaces_and_flags.md'
      - 'Secrets': 'Advanced/SDK/secrets.md'
      - 'Ramble': 'Advanced/SDK/ramble.md'
      - 'Reference':
        - 'Apply':
          - 'Core': 'Advanced/SDK/Reference/apply/core.md'
          - 'Payloads': 'Advanced/SDK/Reference/apply/payloads.md'
        - 'Check':
          - 'Core': 'Advanced/SDK/Reference/check/core.md'
          - 'Payloads': 'Advanced/SDK/Reference/check/payloads.md'
        - 'Common':
          - 'Payloads': 'Advanced/SDK/Reference/common/payloads.md'
        - 'Explain':
          - 'Core': 'Advanced/SDK/Reference/explain/core.md'
          - 'Payloads': 'Advanced/SDK/Reference/explain/payloads.md'
        - 'Init':
          - 'Core': 'Advanced/SDK/Reference/init/core.md'
          - 'Payloads': 'Advanced/SDK/Reference/init/payloads.md'
        - 'Ramble':
          - 'Core': 'Advanced/SDK/Reference/ramble/core.md'
          - 'Payloads': 'Advanced/SDK/Reference/ramble/payloads.md'
        - 'Secrets':
          - 'Core': 'Advanced/SDK/Reference/secrets/core.md'
          - 'Payloads': 'Advanced/SDK/Reference/secrets/payloads.md'
        - 'Set':
          - 'Core': 'Advanced/SDK/Reference/set/core.md'
          - 'Payloads': 'Advanced/SDK/Reference/set/payloads.md'
        - 'Styx':
          - 'Core': 'Advanced/SDK/Reference/styx/core.md'
          - 'Payloads': 'Advanced/SDK/Reference/styx/payloads.md'
        - 'Team':
          - 'Core': 'Advanced/SDK/Reference/team/core.md'
          - 'Payloads': 'Advanced/SDK/Reference/team/payloads.md'
        - 'Boats':
          - 'Core': 'Advanced/SDK/Reference/boats/core.md'
        - 'Limani':
          - 'Core': 'Advanced/SDK/Reference/limani/core.md'
        - 'Roles':
          - 'Core': 'Advanced/SDK/Reference/roles/core.md'
  - 'Souls':
    - 'Provider Souls': 'Souls/provider-plugins.md'
    - 'Registry': 'Souls/styx.md'
    - 'Development': 'Souls/development.md'
    - 'Connector development': 'Souls/connectors.md'
    - 'Roles': 'Souls/roles.md'
    - 'Limani': 'Souls/limani.md'
